package cn.campus.community

import com.zaxxer.hikari.HikariConfig
import com.zaxxer.hikari.HikariDataSource
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import org.flywaydb.core.Flyway
import java.sql.*
import java.time.Instant
import java.util.*

class CommunityDatabase(url:String,user:String,password:String,private val security:Security){
    private val json=Json
    private val ds=HikariDataSource(HikariConfig().apply{jdbcUrl=url;username=user;this.password=password;maximumPoolSize=10;minimumIdle=1;isAutoCommit=true})
    init{Flyway.configure().dataSource(ds).load().migrate()}
    fun close()=ds.close()
    fun bootstrapInvite(code:String?){if(code.isNullOrBlank())return;ds.connection.use{c->c.prepareStatement("INSERT IGNORE INTO invite_codes(code,max_uses,granted_role) VALUES(?,1,'ADMIN')").use{it.setString(1,code);it.executeUpdate()}}}

    fun register(req:RegisterRequest):Pair<PublicUser,Int>{
        val username=req.username.lowercase();validateCredentials(username,req.password)
        val nickname=(req.nickname?.trim().takeUnless{it.isNullOrBlank()}?:username).take(40)
        val email=req.email?.trim()?.lowercase()?.takeUnless{it.isBlank()}
        requireApi(email==null||email.matches(Regex("^[^@\\s]{1,64}@[^@\\s]{1,189}$")),"invalid_email","邮箱格式不正确")
        val hash=security.hashPassword(req.password);val id=UUID.randomUUID().toString()
        return transaction{c->
            val role=c.prepareStatement("SELECT max_uses,used_count,expires_at,granted_role FROM invite_codes WHERE code=? FOR UPDATE").use{q->q.setString(1,req.inviteCode.trim());q.executeQuery().use{r->if(!r.next())throw ApiException(400,"invalid_invite","邀请码无效");val expiry=r.getTimestamp(3)?.toInstant();if(r.getInt(2)>=r.getInt(1)||expiry?.isBefore(Instant.now())==true)throw ApiException(400,"invite_unavailable","邀请码已用完或已过期");r.getString(4)}}
            try{c.prepareStatement("INSERT INTO users(id,username,password_hash,email,nickname,role) VALUES(?,?,?,?,?,?)").use{q->q.setString(1,id);q.setString(2,username);q.setString(3,hash);q.setString(4,email);q.setString(5,nickname);q.setString(6,role);q.executeUpdate()}}catch(e:SQLIntegrityConstraintViolationException){throw ApiException(409,"account_exists","用户名或邮箱已被使用")}
            c.prepareStatement("UPDATE invite_codes SET used_count=used_count+1 WHERE code=?").use{it.setString(1,req.inviteCode.trim());it.executeUpdate()}
            PublicUser(id,username,nickname,role) to 0
        }
    }
    fun login(username:String,password:String):Triple<PublicUser,Int,String>{
        ds.connection.use{c->c.prepareStatement("SELECT id,username,nickname,role,status,token_epoch,password_hash FROM users WHERE username=?").use{q->q.setString(1,username.lowercase());q.executeQuery().use{r->if(!r.next()||!security.verifyPassword(r.getString(7),password))throw ApiException(401,"invalid_credentials","用户名或密码不正确");if(r.getString(5)!="ACTIVE")throw ApiException(403,"account_unavailable","账号不可用");return Triple(PublicUser(r.getString(1),r.getString(2),r.getString(3),r.getString(4)),r.getInt(6),r.getString(5))}}}
    }
    fun user(id:String):Pair<PublicUser,Int>{ds.connection.use{c->c.prepareStatement("SELECT username,nickname,role,status,token_epoch FROM users WHERE id=?").use{q->q.setString(1,id);q.executeQuery().use{r->if(!r.next()||r.getString(4)!="ACTIVE")throw ApiException(401,"session_invalid","登录状态已失效");return PublicUser(id,r.getString(1),r.getString(2),r.getString(3)) to r.getInt(5)}}}}
    fun saveRefresh(userId:String,familyId:String=UUID.randomUUID().toString()):String{val id=UUID.randomUUID().toString();val secret=security.randomSecret();ds.connection.use{c->c.prepareStatement("INSERT INTO refresh_tokens(id,user_id,family_id,secret_hash,expires_at) VALUES(?,?,?,?,DATE_ADD(NOW(3),INTERVAL 30 DAY))").use{q->q.setString(1,id);q.setString(2,userId);q.setString(3,familyId);q.setString(4,security.sha256(secret));q.executeUpdate()}};return "$id.$secret"}
    fun rotateRefresh(token:String):Triple<PublicUser,Int,String>{val parts=token.split('.',limit=2);if(parts.size!=2)throw ApiException(401,"refresh_invalid","登录状态已失效");return transaction{c->c.prepareStatement("SELECT user_id,family_id,secret_hash,expires_at,revoked_at FROM refresh_tokens WHERE id=? FOR UPDATE").use{q->q.setString(1,parts[0]);q.executeQuery().use{r->if(!r.next())throw ApiException(401,"refresh_invalid","登录状态已失效");val userId=r.getString(1);val family=r.getString(2);if(r.getTimestamp(5)!=null||r.getTimestamp(4).toInstant().isBefore(Instant.now())||r.getString(3)!=security.sha256(parts[1])){c.prepareStatement("UPDATE refresh_tokens SET revoked_at=COALESCE(revoked_at,NOW(3)) WHERE family_id=?").use{it.setString(1,family);it.executeUpdate()};throw ApiException(401,"refresh_reused","登录状态已失效，请重新登录")};val fresh=saveRefreshIn(c,userId,family);c.prepareStatement("UPDATE refresh_tokens SET revoked_at=NOW(3),replaced_by=? WHERE id=?").use{it.setString(1,fresh.first);it.setString(2,parts[0]);it.executeUpdate()};val (u,e)=userIn(c,userId);Triple(u,e,"${fresh.first}.${fresh.second}")}}}}
    fun revokeAll(userId:String){transaction<Unit>{c->c.prepareStatement("UPDATE refresh_tokens SET revoked_at=COALESCE(revoked_at,NOW(3)) WHERE user_id=?").use{it.setString(1,userId);it.executeUpdate()};c.prepareStatement("UPDATE users SET token_epoch=token_epoch+1 WHERE id=?").use{it.setString(1,userId);it.executeUpdate()}}}
    fun deleteAccount(userId:String){transaction<Unit>{c->revokeAllIn(c,userId);c.prepareStatement("UPDATE users SET status='DELETED',deleted_at=NOW(3),email=NULL,nickname='已注销用户' WHERE id=?").use{it.setString(1,userId);it.executeUpdate()};c.prepareStatement("UPDATE posts SET hidden=TRUE,deleted_at=COALESCE(deleted_at,NOW(3)) WHERE author_id=?").use{it.setString(1,userId);it.executeUpdate()}}}

    fun listPosts(cursor:String?,query:String?,limit:Int,userId:String?,authorId:String?=null,favoriteUserId:String?=null):PageResponse<PostSummary>{
        val safe=limit.coerceIn(1,30);val params=mutableListOf<Any>();val where=StringBuilder("p.hidden=FALSE AND p.deleted_at IS NULL")
        authorId?.let{where.append(" AND p.author_id=?");params+=it};favoriteUserId?.let{where.append(" AND EXISTS(SELECT 1 FROM favorites chosen WHERE chosen.post_id=p.id AND chosen.user_id=?)");params+=it};cursor?.let{where.append(" AND p.created_at < ?");params+=Timestamp.from(Instant.parse(it))};query?.trim()?.takeIf{it.isNotBlank()}?.let{where.append(" AND (p.title LIKE ? OR p.body LIKE ?)");params+="%$it%";params+="%$it%"}
        val sql="""SELECT p.id,p.title,LEFT(p.body,180),p.format,p.tags_json,p.version,p.created_at,p.updated_at,u.id,u.username,u.nickname,u.role,(SELECT COUNT(*) FROM favorites f WHERE f.post_id=p.id),(SELECT COUNT(*) FROM comments c WHERE c.post_id=p.id AND c.deleted_at IS NULL),${if(userId==null)"FALSE" else "EXISTS(SELECT 1 FROM favorites me WHERE me.post_id=p.id AND me.user_id=?)"} FROM posts p JOIN users u ON u.id=p.author_id WHERE $where ORDER BY p.created_at DESC LIMIT ?"""
        ds.connection.use{c->c.prepareStatement(sql).use{q->var i=1;if(userId!=null)q.setString(i++,userId);params.forEach{q.setObject(i++,it)};q.setInt(i,safe+1);q.executeQuery().use{r->val all=mutableListOf<PostSummary>();while(r.next())all+=postRow(r);val more=all.size>safe;val items=all.take(safe);return PageResponse(items,if(more)items.last().createdAt else null)}}}
    }
    fun postDetail(id:String,userId:String?):PostDetail{val post=listPostsById(id,userId);val comments=mutableListOf<CommentView>();ds.connection.use{c->c.prepareStatement("SELECT c.id,c.body,c.created_at,u.id,u.username,u.nickname,u.role FROM comments c JOIN users u ON u.id=c.author_id WHERE c.post_id=? AND c.deleted_at IS NULL ORDER BY c.created_at").use{q->q.setString(1,id);q.executeQuery().use{r->while(r.next())comments+=CommentView(r.getString(1),r.getString(2),PublicUser(r.getString(4),r.getString(5),r.getString(6),r.getString(7)),r.getTimestamp(3).toInstant().toString())}}};val body=ds.connection.use{c->c.prepareStatement("SELECT body FROM posts WHERE id=?").use{q->q.setString(1,id);q.executeQuery().use{r->r.next();r.getString(1)}}};return PostDetail(post,body,comments)}
    fun createPost(userId:String,w:PostWrite):PostDetail{validatePost(w);val id=UUID.randomUUID().toString();ds.connection.use{c->c.prepareStatement("INSERT INTO posts(id,author_id,title,body,format,tags_json) VALUES(?,?,?,?,?,?)").use{q->q.setString(1,id);q.setString(2,userId);q.setString(3,w.title.trim());q.setString(4,sanitize(w.body));q.setString(5,w.format.uppercase());q.setString(6,json.encodeToString(w.tags.map{it.trim().take(20)}.filter{it.isNotBlank()}.take(5)));q.executeUpdate()}};return postDetail(id,userId)}
    fun updatePost(userId:String,id:String,w:PostWrite):PostDetail{validatePost(w);val version=w.version?:throw ApiException(400,"version_required","缺少帖子版本号");ds.connection.use{c->c.prepareStatement("UPDATE posts SET title=?,body=?,format=?,tags_json=?,version=version+1,updated_at=NOW(3) WHERE id=? AND author_id=? AND version=? AND deleted_at IS NULL").use{q->q.setString(1,w.title.trim());q.setString(2,sanitize(w.body));q.setString(3,w.format.uppercase());q.setString(4,json.encodeToString(w.tags.take(5)));q.setString(5,id);q.setString(6,userId);q.setInt(7,version);if(q.executeUpdate()!=1)throw ApiException(409,"version_conflict","帖子已在其他位置更新，请刷新后重试")}};return postDetail(id,userId)}
    fun deletePost(userId:String,id:String){ds.connection.use{c->c.prepareStatement("UPDATE posts SET deleted_at=NOW(3) WHERE id=? AND author_id=? AND deleted_at IS NULL").use{q->q.setString(1,id);q.setString(2,userId);if(q.executeUpdate()!=1)throw ApiException(404,"post_not_found","帖子不存在或无权删除")}}}
    fun favorite(userId:String,id:String,value:Boolean){ds.connection.use{c->if(value)c.prepareStatement("INSERT IGNORE INTO favorites(user_id,post_id) SELECT ?,id FROM posts WHERE id=? AND hidden=FALSE AND deleted_at IS NULL").use{it.setString(1,userId);it.setString(2,id);it.executeUpdate()}else c.prepareStatement("DELETE FROM favorites WHERE user_id=? AND post_id=?").use{it.setString(1,userId);it.setString(2,id);it.executeUpdate()}}}
    fun addComment(userId:String,postId:String,body:String):CommentView{val clean=body.trim();requireApi(clean.isNotBlank()&&clean.length<=500,"invalid_comment","评论需为1至500字");val id=UUID.randomUUID().toString();ds.connection.use{c->c.prepareStatement("INSERT INTO comments(id,post_id,author_id,body) SELECT ?,?,?,? FROM posts WHERE id=? AND hidden=FALSE AND deleted_at IS NULL").use{q->q.setString(1,id);q.setString(2,postId);q.setString(3,userId);q.setString(4,clean);q.setString(5,postId);if(q.executeUpdate()!=1)throw ApiException(404,"post_not_found","帖子不存在")}};val user=user(userId).first;return CommentView(id,clean,user,Instant.now().toString())}
    fun deleteComment(userId:String,id:String){ds.connection.use{c->c.prepareStatement("UPDATE comments SET deleted_at=NOW(3) WHERE id=? AND author_id=? AND deleted_at IS NULL").use{it.setString(1,id);it.setString(2,userId);if(it.executeUpdate()!=1)throw ApiException(404,"comment_not_found","评论不存在或无权删除")}}}
    fun report(userId:String,r:ReportRequest){requireApi(r.targetType in listOf("POST","COMMENT")&&r.reason.trim().length in 2..300,"invalid_report","请填写2至300字的举报原因");ds.connection.use{c->c.prepareStatement("INSERT INTO reports(id,reporter_id,target_type,target_id,reason) VALUES(?,?,?,?,?)").use{it.setString(1,UUID.randomUUID().toString());it.setString(2,userId);it.setString(3,r.targetType);it.setString(4,r.targetId);it.setString(5,r.reason.trim());it.executeUpdate()}}}
    fun createInvite(adminId:String,r:InviteRequest){requireApi(r.code.matches(Regex("[A-Za-z0-9_-]{6,32}"))&&r.maxUses in 1..100,"invalid_invite","邀请码格式或使用次数不正确");ds.connection.use{c->c.prepareStatement("INSERT INTO invite_codes(code,max_uses,expires_at,created_by) VALUES(?,?,?,?)").use{it.setString(1,r.code);it.setInt(2,r.maxUses);it.setTimestamp(3,r.expiresAt?.let{v->Timestamp.from(Instant.parse(v))});it.setString(4,adminId);it.executeUpdate()}}}
    fun reports():List<AdminReport>{val out=mutableListOf<AdminReport>();ds.connection.use{c->c.prepareStatement("SELECT r.id,u.username,r.target_type,r.target_id,r.reason,r.status,r.created_at FROM reports r JOIN users u ON u.id=r.reporter_id ORDER BY r.created_at DESC LIMIT 200").use{q->q.executeQuery().use{r->while(r.next())out+=AdminReport(r.getString(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6),r.getTimestamp(7).toInstant().toString())}}};return out}
    fun moderate(adminId:String,targetId:String,r:ModerateRequest){transaction<Unit>{c->when(r.action){"HIDE_POST"->c.prepareStatement("UPDATE posts SET hidden=TRUE WHERE id=?").use{it.setString(1,targetId);it.executeUpdate()};"DELETE_COMMENT"->c.prepareStatement("UPDATE comments SET deleted_at=NOW(3) WHERE id=?").use{it.setString(1,targetId);it.executeUpdate()};"BAN_USER"->c.prepareStatement("UPDATE users SET status='BANNED',token_epoch=token_epoch+1 WHERE id=?").use{it.setString(1,targetId);it.executeUpdate()};"RESOLVE_REPORT"->c.prepareStatement("UPDATE reports SET status='RESOLVED',resolved_by=?,resolved_at=NOW(3) WHERE id=?").use{it.setString(1,adminId);it.setString(2,targetId);it.executeUpdate()};else->throw ApiException(400,"invalid_action","不支持的管理操作")};c.prepareStatement("INSERT INTO moderation_audit(admin_id,action,target_id,detail) VALUES(?,?,?,?)").use{it.setString(1,adminId);it.setString(2,r.action);it.setString(3,targetId);it.setString(4,r.reason.take(500));it.executeUpdate()}}}

    private fun listPostsById(id:String,userId:String?):PostSummary{val sql="""SELECT p.id,p.title,LEFT(p.body,180),p.format,p.tags_json,p.version,p.created_at,p.updated_at,u.id,u.username,u.nickname,u.role,(SELECT COUNT(*) FROM favorites f WHERE f.post_id=p.id),(SELECT COUNT(*) FROM comments c WHERE c.post_id=p.id AND c.deleted_at IS NULL),${if(userId==null)"FALSE" else "EXISTS(SELECT 1 FROM favorites me WHERE me.post_id=p.id AND me.user_id=?)"} FROM posts p JOIN users u ON u.id=p.author_id WHERE p.id=? AND p.hidden=FALSE AND p.deleted_at IS NULL""";ds.connection.use{c->c.prepareStatement(sql).use{q->var i=1;if(userId!=null)q.setString(i++,userId);q.setString(i,id);q.executeQuery().use{r->if(!r.next())throw ApiException(404,"post_not_found","帖子不存在");return postRow(r)}}}}
    private fun postRow(r:ResultSet)=PostSummary(
        id=r.getString(1),title=r.getString(2),excerpt=r.getString(3),format=r.getString(4),
        tags=runCatching{json.decodeFromString<List<String>>(r.getString(5))}.getOrDefault(emptyList()),
        author=PublicUser(r.getString(9),r.getString(10),r.getString(11),r.getString(12)),
        version=r.getInt(6),favoriteCount=r.getInt(13),commentCount=r.getInt(14),
        createdAt=r.getTimestamp(7).toInstant().toString(),updatedAt=r.getTimestamp(8).toInstant().toString(),favored=r.getBoolean(15)
    )
    private fun validatePost(w:PostWrite){requireApi(w.title.trim().length in 1..80,"invalid_title","标题需为1至80字");requireApi(w.body.length in 1..20000,"invalid_body","正文需为1至20000字");requireApi(w.format.uppercase() in listOf("PLAIN","MARKDOWN"),"invalid_format","正文格式不支持")}
    private fun sanitize(body:String)=body
        .replace(Regex("(?is)<[^>]+>"),"")
        .replace(Regex("!\\[[^]]*]\\([^)]*\\)"),"[图片已移除]")
        .replace(Regex("\\[([^]]+)]\\((?!https://)[^)]+\\)"),"$1 [非HTTPS链接已移除]")
        .replace(Regex("(?i)http://\\S+"),"[非HTTPS链接已移除]")
    private fun validateCredentials(u:String,p:String){requireApi(u.matches(Regex("[a-z0-9_]{4,20}")),"invalid_username","用户名需为4至20位字母、数字或下划线");requireApi(p.length in 10..72,"invalid_password","密码需为10至72位")}
    private fun requireApi(ok:Boolean,code:String,message:String){if(!ok)throw ApiException(400,code,message)}
    private fun saveRefreshIn(c:Connection,userId:String,family:String):Pair<String,String>{val id=UUID.randomUUID().toString();val secret=security.randomSecret();c.prepareStatement("INSERT INTO refresh_tokens(id,user_id,family_id,secret_hash,expires_at) VALUES(?,?,?,?,DATE_ADD(NOW(3),INTERVAL 30 DAY))").use{it.setString(1,id);it.setString(2,userId);it.setString(3,family);it.setString(4,security.sha256(secret));it.executeUpdate()};return id to secret}
    private fun userIn(c:Connection,id:String):Pair<PublicUser,Int>{c.prepareStatement("SELECT username,nickname,role,status,token_epoch FROM users WHERE id=?").use{it.setString(1,id);it.executeQuery().use{r->if(!r.next()||r.getString(4)!="ACTIVE")throw ApiException(401,"session_invalid","登录状态已失效");return PublicUser(id,r.getString(1),r.getString(2),r.getString(3)) to r.getInt(5)}}}
    private fun revokeAllIn(c:Connection,id:String){c.prepareStatement("UPDATE refresh_tokens SET revoked_at=COALESCE(revoked_at,NOW(3)) WHERE user_id=?").use{it.setString(1,id);it.executeUpdate()};c.prepareStatement("UPDATE users SET token_epoch=token_epoch+1 WHERE id=?").use{it.setString(1,id);it.executeUpdate()}}
    private fun <T> transaction(block:(Connection)->T):T=ds.connection.use{c->c.autoCommit=false;try{block(c).also{c.commit()}}catch(e:Throwable){c.rollback();throw e}finally{c.autoCommit=true}}
}
