import http from "node:http";
import { mkdirSync } from "node:fs";
import { DatabaseSync } from "node:sqlite";
import webpush from "web-push";

const port=Number(process.env.PORT||8080),dataDir=process.env.DATA_DIR||"./data",allowed=(process.env.ALLOWED_ORIGINS||"https://xiaoyle.github.io").split(",").map(x=>x.trim());
for(const name of ["VAPID_PUBLIC_KEY","VAPID_PRIVATE_KEY","VAPID_SUBJECT"])if(!process.env[name])throw Error(`Missing ${name}`);
mkdirSync(dataDir,{recursive:true});const db=new DatabaseSync(`${dataDir}/push.sqlite`);db.exec(`PRAGMA journal_mode=WAL;CREATE TABLE IF NOT EXISTS subscriptions(device_token TEXT PRIMARY KEY,subscription_json TEXT NOT NULL,updated_at INTEGER NOT NULL);CREATE TABLE IF NOT EXISTS reminders(id TEXT NOT NULL,device_token TEXT NOT NULL,trigger_at INTEGER NOT NULL,ciphertext TEXT NOT NULL,iv TEXT NOT NULL,sent_at INTEGER,PRIMARY KEY(id,device_token),FOREIGN KEY(device_token) REFERENCES subscriptions(device_token) ON DELETE CASCADE);CREATE INDEX IF NOT EXISTS idx_due ON reminders(trigger_at,sent_at);`);
webpush.setVapidDetails(process.env.VAPID_SUBJECT,process.env.VAPID_PUBLIC_KEY,process.env.VAPID_PRIVATE_KEY);
const hits=new Map();function limited(ip){const now=Date.now(),old=hits.get(ip)??[];const fresh=old.filter(x=>x>now-60000);fresh.push(now);hits.set(ip,fresh);return fresh.length>80}
function json(res,status,value,origin){res.writeHead(status,{"Content-Type":"application/json;charset=utf-8","Access-Control-Allow-Origin":origin,"Vary":"Origin","Access-Control-Allow-Methods":"GET,POST,DELETE,OPTIONS","Access-Control-Allow-Headers":"Content-Type","Cache-Control":"no-store"});res.end(JSON.stringify(value))}
async function body(req){let size=0,text="";for await(const chunk of req){size+=chunk.length;if(size>2_000_000)throw Object.assign(Error("too_large"),{status:413});text+=chunk}return JSON.parse(text||"{}")}
function validToken(x){return typeof x==="string"&&/^[a-zA-Z0-9-]{20,80}$/.test(x)}
const server=http.createServer(async(req,res)=>{const origin=allowed.includes(req.headers.origin)?req.headers.origin:allowed[0];if(req.method==="OPTIONS")return json(res,204,{},origin);if(limited(req.socket.remoteAddress||"unknown"))return json(res,429,{error:"too_many_requests"},origin);try{const url=new URL(req.url,"http://local");if(url.pathname==="/health")return json(res,200,{status:"ok",version:"0.1.0"},origin);if(req.method==="POST"&&url.pathname==="/v1/push/subscriptions"){const input=await body(req);if(!validToken(input.deviceToken)||typeof input.subscription?.endpoint!=="string"||!Array.isArray(input.reminders)||input.reminders.length>500)throw Object.assign(Error("invalid_request"),{status:400});const now=Date.now();db.exec("BEGIN");try{db.prepare("INSERT INTO subscriptions(device_token,subscription_json,updated_at) VALUES(?,?,?) ON CONFLICT(device_token) DO UPDATE SET subscription_json=excluded.subscription_json,updated_at=excluded.updated_at").run(input.deviceToken,JSON.stringify(input.subscription),now);db.prepare("DELETE FROM reminders WHERE device_token=? AND sent_at IS NULL").run(input.deviceToken);const insert=db.prepare("INSERT OR REPLACE INTO reminders(id,device_token,trigger_at,ciphertext,iv,sent_at) VALUES(?,?,?,?,?,NULL)");for(const r of input.reminders){const trigger=Date.parse(r.triggerAt);if(typeof r.id!=="string"||r.id.length>240||!Number.isFinite(trigger)||trigger<now-60000||trigger>now+370*86400000||typeof r.ciphertext!=="string"||typeof r.iv!=="string")throw Object.assign(Error("invalid_reminder"),{status:400});insert.run(r.id,input.deviceToken,trigger,r.ciphertext,r.iv)}db.exec("COMMIT")}catch(e){db.exec("ROLLBACK");throw e}return json(res,200,{status:"ok",scheduled:input.reminders.length},origin)}const match=url.pathname.match(/^\/v1\/push\/subscriptions\/([^/]+)$/);if(req.method==="DELETE"&&match){const token=decodeURIComponent(match[1]);if(!validToken(token))throw Object.assign(Error("invalid_token"),{status:400});db.prepare("DELETE FROM reminders WHERE device_token=?").run(token);db.prepare("DELETE FROM subscriptions WHERE device_token=?").run(token);return json(res,200,{status:"deleted"},origin)}return json(res,404,{error:"not_found"},origin)}catch(e){json(res,e.status||500,{error:e.message==="Unexpected end of JSON input"?"invalid_json":e.message||"internal_error"},origin)}});
async function dispatch(){const now=Date.now(),rows=db.prepare("SELECT r.id,r.device_token,r.ciphertext,r.iv,s.subscription_json FROM reminders r JOIN subscriptions s ON s.device_token=r.device_token WHERE r.sent_at IS NULL AND r.trigger_at<=? ORDER BY r.trigger_at LIMIT 100").all(now);for(const row of rows){try{await webpush.sendNotification(JSON.parse(row.subscription_json),JSON.stringify({id:row.id,ciphertext:row.ciphertext,iv:row.iv}),{TTL:3600,urgency:"normal"});db.prepare("UPDATE reminders SET sent_at=? WHERE id=? AND device_token=?").run(Date.now(),row.id,row.device_token)}catch(e){if(e.statusCode===404||e.statusCode===410){db.prepare("DELETE FROM reminders WHERE device_token=?").run(row.device_token);db.prepare("DELETE FROM subscriptions WHERE device_token=?").run(row.device_token)}else console.error("push_failed",e.statusCode||e.name)}}db.prepare("DELETE FROM reminders WHERE sent_at IS NOT NULL AND sent_at<?").run(now-7*86400000);db.prepare("DELETE FROM reminders WHERE sent_at IS NULL AND trigger_at<?").run(now-86400000)}
setInterval(()=>dispatch().catch(e=>console.error("dispatch_failed",e.name)),15000).unref();server.listen(port,"0.0.0.0",()=>console.log(`push service listening on ${port}`));
