import { chromium, expect } from "@playwright/test";
import { mkdirSync } from "node:fs";
mkdirSync("../.tools", { recursive: true });
const browser = await chromium.launch({ channel: "msedge", headless: true });
const context = await browser.newContext({ viewport: { width: 390, height: 844 } });
const page = await context.newPage(), errors = [];
page.on("pageerror", (error) => errors.push(error.message));
await page.goto("http://127.0.0.1:4173/CampusSchedule/");
await page.getByRole("button", { name: "我的" }).click();
await page.getByRole("button", { name: /课表与导入/ }).click();
await page.locator('input[accept=".doc,.docx,.pdf,.json"]').setInputFiles("../private-fixtures/schedule.pdf");
await expect(page.getByRole("dialog")).toContainText("29");
await expect(page.getByRole("dialog")).toContainText("17");
await page.getByRole("button", { name: "确认保存" }).click();
await expect(page.getByText("课表已保存到本机")).toBeVisible();
await page.getByRole("button", { name: "返回" }).click();
await page.getByRole("button", { name: "计划" }).click();
await expect(page.locator(".lesson-card").first()).toBeVisible();
await page.screenshot({ path: "../.tools/pwa-plan.png", fullPage: true });
await page.getByRole("button", { name: "待办", exact: true }).click();
await page.locator(".page-action button").click();
await page.getByLabel("任务标题").fill("网页测试待办");
await page.locator(".page-action button").click();
await page.getByRole("button", { name: "计划" }).click();
await page.getByRole("button", { name: "待办", exact: true }).click();
await expect(page.getByText("网页测试待办")).toBeVisible();
await page.reload();
await page.getByRole("button", { name: "计划" }).click();
await page.getByRole("button", { name: "周课表", exact: true }).click();
await expect(page.locator(".lesson-card").first()).toBeVisible();
await page.waitForFunction(() => navigator.serviceWorker.controller !== null);
await context.setOffline(true); await page.reload();
await page.getByRole("button", { name: "计划" }).click();
await page.getByRole("button", { name: "周课表", exact: true }).click();
await expect(page.locator(".lesson-card").first()).toBeVisible();
await context.setOffline(false);
for (const width of [320, 390, 768, 1280]) {
  await page.setViewportSize({ width, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
}
expect(errors).toEqual([]);
console.log("PASS: PWA import 29/17, task persistence, offline reopen, responsive widths, no page errors");
await browser.close();
